export default [
	{
		read: false,
		img: 'avatar-mark-webber.webp',
		name: 'Mark Webber',
		action: 'reacted to your recent post',
		actionLink: 'My first tournament today!',
		actionFor: 'post',
		time: '1m ago',
	},
	{
		read: false,
		img: 'avatar-angela-gray.webp',
		name: 'Angela Gray',
		action: 'followed you',
		time: '5m ago',
	},
	{
		read: false,
		img: 'avatar-jacob-thompson.webp',
		name: 'Jacob Thompson',
		action: 'has joined your group',
		actionLink: 'Chess Club',
		actionFor: 'group',
		time: '1 day ago',
	},
	{
		read: true,
		img: 'avatar-rizky-hasanuddin.webp',
		name: 'Rizky Hasanuddin',
		action: 'sent you a private message',
		time: '5 days ago',
		message:
			'Hello, thanks for setting up the Chess Club. I’ve been a member for a few weeks now and I’m already having lots of fun and improving my game.',
	},
	{
		read: true,
		img: 'avatar-kimberly-smith.webp',
		name: 'Kimberly Smith',
		action: 'commented on your picture',
		actionImg: 'image-chess.webp',
		time: '1 week ago',
	},
	{
		read: true,
		img: 'avatar-nathan-peterson.webp',
		name: 'Nathan Peterson',
		action: 'reacted to your recent post',
		actionLink: '5 end-game strategies to increase your win rate',
		actionFor: 'post',
		time: '2 weeks ago',
	},
	{
		read: true,
		img: 'avatar-anna-kim.webp',
		name: 'Anna Kim',
		action: 'left the group',
		actionLink: 'Chess Club',
		actionFor: 'group',
		time: '2 weeks ago',
	},
]
